---
- hosts: all
  become: yes
  tasks:
    - name: Pull frontend Docker image
      docker_image:
        name: "{{ DOCKER_USERNAME }}/jobapp-ci-frontend"
        tag: "v{{ BUILD_NUMBER }}"
        source: pull

    - name: Pull backend Docker image
      docker_image:
        name: "{{ DOCKER_USERNAME }}/jobapp-ci-backend"
        tag: "v{{ BUILD_NUMBER }}"
        source: pull

    - name: Run frontend Docker container
      docker_container:
        name: frontend
        image: "{{ DOCKER_USERNAME }}/jobapp-ci-frontend:v{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8086:5173"

    - name: Run backend Docker container
      docker_container:
        name: backend
        image: "{{ DOCKER_USERNAME }}/jobapp-ci-backend:v{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8087:4000"
